name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ping_server:
              - 'ping_server/**'
  test-ping-server:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.pint_server == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      - run: ping_server/test.sh
